spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/skhuming-backend;
    username: sa
    password:
    driver-class-name: org.h2.Driver
